n_obs_states: 49
n_actions: 4
init_model_config: None
tpc_model_config: None
test_inf_iters: 5
inf_iters: 5
inf_lr: 0.001
device: 'cpu'
hidden_dim: 512
batch_size: 64
learning_rate: 0.005
gamma: 0.9
learn: False
reward_lr: 0.01
learn_rewards_from_state: True
plan_steps: 1
inverse_temp: 1.0
exploration_eps: -1
sr_estimate_planning: 'uniform'
sr_early_stop_uniform: None
sr_early_stop_goal:  None
seed: 42