room: [
  [  # colors (negative for obstacles)
    [ 1, 2, 2, 3, 0],
    [ 0, 1, 3, 2, 3],
    [ -2, -2, -2, 0, 0],
    [ 0, 2, 1, 1, 3],
    [ 1, 3, 1, 0, 1],
  ],
  [ # rewards
    [ 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0]
  ],
  [ # terminal states (set 1 to specify terminal states)
    [ 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0],
    [ 0, 0, 0, 0, 0]
  ],
  [ # landmarks (set 1 to specify landmarks)
    [ 0, 0, 0, 0, 0 ],
    [ 0, 0, 0, 0, 0 ],
    [ 0, 0, 0, 0, 0 ],
    [ 0, 0, 0, 0, 0 ],
    [ 0, 0, 0, 0, 0 ]
  ]
]
# comment if you want agent to start from random position
start_position: [4, 0]